---
- name: Create the server hud server service file.
  template:
    src: serverhud-server.service.j2
    dest: "{{ systemd_service_dir }}/serverhud-server.service"
  when: serverhud_install_server
  notify:
      - Reload systemd service files
      - Restart server hud server
  become: yes
