---
- name: Create the server hud server service file.
  template:
    src: serverhud-server.service.j2
    dest: "{{ systemd_service_dir }}/serverhud-server.service"
  when: serverhud_install_server
  notify: Restart server hud server
  become: yes

- name: Create the server hud client service file.
  template:
    src: serverhud-client.service.j2
    dest: "{{ systemd_service_dir }}/serverhud-client.service"
  when: serverhud_install_client
  notify: Restart server hud client
  become: yes
