---
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install Debian packages needed for serverhud installation.
  apt:
    name: "{{ item }}"
    state: "{{ serverhud_packagess_state }}"
  with_items: "{{ serverhud_packages }}"
  become: yes
