---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install OS-specific packages
  include_tasks: "{{ ansible_os_family }}-install.yml"

- name: Install server hud
  include_tasks: "serverhud-install.yml"

- name: Configure server hud
  include_tasks: "serverhud-config.yml"

- name: Configure OS-specific settings
  include_tasks: "{{ ansible_os_family }}-config.yml"

- name: Setup server hud services
  include_tasks: "serverhud-service.yml"
