---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install OS-specific packages
  include_tasks: "{{ ansible_distribution }}-install.yml"

- name: Install server hud server
  include_tasks: "serverhud-install-server.yml"
  when: serverhud_install_server

- name: Install server hud client
  include_tasks: "serverhud-install-client.yml"
  when: serverhud_install_client

- name: Configure server hud
  include_tasks: "serverhud-config.yml"

- name: Configure OS-specific settings
  include_tasks: "{{ ansible_distribution }}-config.yml"

- name: Setup server hud services
  include_tasks: "serverhud-service.yml"
  when: serverhud_install_server
