---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: "{{ ansible_os_family }}-setup.yml"

- name: "Push ssh key to {{ serverhud_user }} user"
  authorized_key:
    user: "{{ serverhud_user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
  become: yes

- name: Install server hud
  include: "serverhud-install.yml"

- name: "Remove key from the {{ serverhud_user }} user"
  authorized_key:
    user: "{{ serverhud_user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: absent
  become: yes
