---
- name: "Add {{ serverhud_group }} group"
  group:
    name: "{{ serverhud_group }}"
    state: present
  become: yes

- name: "Add {{ serverhud_user }} user"
  user:
    name: "{{ serverhud_user }}"
    createhome: yes
    group: "{{ serverhud_group }}"
    home: "{{ serverhud_home_dir }}"
    system: yes
  become: yes

- name: Install the server hud package
  pip:
    name: "{{ serverhud_pip_uri }}"
    executable: "{{ pip_executable }}"
  notify:
    - Restart server hud server
    - Restart server hud client
