---
- name: Enable the server hud server service.
  service:
    name: "{{ serverhud_server_service }}"
    state: "{{ serverhud_state }}"
  when: serverhud_install_server
  notify: Restart server hud server
  become: yes
