# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "debian/stretch64"

  # Disable synced folders, to not have the Debian default install to not enter
  # an endless recursive dive starting from the symlink in test.
  config.vm.synced_folder ".", "/vagrant", disabled: true


  # spin up vms
  vms = [
      {
          :name => 'server-serverhud',
          :nat_port => 2222
      },
      {
          :name => 'client-serverhud',
          :nat_port => 2223
      }
    ]
  vms.each do |machine_def|
    config.vm.define machine_def[:name] do |machine|
          machine.vm.hostname = machine_def[:name]
          machine.vm.network :forwarded_port, guest: 22, host: machine_def[:nat_port], id: 'ssh'
    end
  end

  # define provisioning
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.raw_arguments = ['-vvv']
    ansible.host_vars = {
        "server-serverhud" => {
            "serverhud_install_client" => false,
        },
        "client-serverhud" => {
            "serverhud_install_server" => false,
        }
    }
    # ansible.groups = {
    #       "servers" => ["srv-a"],
    #       "workstations"  => ["ws-a"]
    # }
  end
end
