# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "debian/stretch64"

  # Disable synced folders, to not have the Debian default install to not enter
  # an endless recursive dive starting from the symlink in test.
  config.vm.synced_folder ".", "/vagrant", disabled: true


  # spin up vms
  vms = [
      {
          :name => 'server-serverhud',
          :nat_port => 2222
      },
      {
          :name => 'client-serverhud',
          :nat_port => 2223
      }
    ]
  vms.each do |machine_def|
    config.vm.define machine_def[:name] do |machine|
          machine.vm.hostname = machine_def[:name]
          machine.vm.network :forwarded_port, guest: 22, host: machine_def[:nat_port], id: 'ssh'
    end
  end

  # define provisioning
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.host_vars = {
        "server-serverhud" => {
            "serverhud_install_client" => false,
            "serverhud_allowed" => "[getfqdn() + ':5000', gethostname() + ':5000', 'localhost:5000', 'client-serverhud:5000']",
            "serverhud_client_host": "{'web_connections': 'server-serverhud:5000', \
                     'web_remote_host': 'server-serverhud:5000', \
                     'web_uptime': 'server-serverhud:5000', \
                     'web_accesses': 'server-serverhud:5000', \
                     'fw_connections': 'server-serverhud:5000', \
                     'fw_speed': 'server-serverhud:5000'}"
        },
        "client-serverhud" => {
            "serverhud_install_server" => false,
            "serverhud_allowed" => "[getfqdn() + ':5000', gethostname() + ':5000', 'localhost:5000', 'server-serverhud:5000']",
            "serverhud_server_process" => "lighttpd",
            "serverhud_server_access" => "/var/log/lighttpd/access.log",
            "serverhud_server_interface" => "eth0",
            "serverhud_server_port" => "80",
            "serverhud_server_services" => "['connections', 'uptime', 'remote_host', 'accesses']"
        }
    }
  end
end
