---
- name: Reload systemd service files
  systemd:
    daemon_reload: yes
  become: yes
  state: reloaded

- name: Restart server hud server
  service:
    name: "{{ serverhud_server_service }}"
  become: yes
  state: "{{ serverhud_restart_state }}"
